server:
  port: 9002

spring:
  application:
    name: ACTIVITY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost


feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000

employee-url: http://localhost:9001/api/employee/