server:
  port: 9001

spring:
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000